#!/usr/bin/env python3
"""
Upload commerce_brain_index.json to Adobe I/O Files.
Run once after building/refreshing the index.

Requires: pip3 install requests
Credentials come from app-builder/.env (generated by aio app init)
"""

import os
import sys
from pathlib import Path
import requests

INDEX_FILE = Path(__file__).parent / "commerce_brain_index.json"
ENV_FILE   = Path(__file__).parent / "app-builder" / ".env"
FILE_NAME  = "commerce_brain_index.json"


def load_env():
    env = {}
    if not ENV_FILE.exists():
        return env
    for line in ENV_FILE.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, _, v = line.partition("=")
            env[k.strip()] = v.strip()
    return env


def get_access_token(env):
    """Exchange service credentials for an IMS access token."""
    r = requests.post(
        "https://ims-na1-stg1.adobelogin.com/ims/token/v3",
        data={
            "grant_type": "client_credentials",
            "client_id": env["SERVICE_API_KEY"],
            "client_secret": env.get("SERVICE_API_SECRET", ""),
            "scope": "AdobeID,openid,adobeio_api,adobeio.appbuilder.project.write",
        },
        timeout=15,
    )
    r.raise_for_status()
    return r.json()["access_token"]


def upload_to_files(token, org_id, project_id, workspace_id, data):
    """Upload bytes to Adobe I/O Files using the Files API."""
    url = f"https://aio-lib-files.adobeioruntime.net/v1/files/{FILE_NAME}"
    headers = {
        "Authorization": f"Bearer {token}",
        "x-gw-ims-org-id": org_id,
        "x-api-key": project_id,
        "Content-Type": "application/json",
    }
    r = requests.put(url, headers=headers, data=data, timeout=60)
    return r


def main():
    if not INDEX_FILE.exists():
        print(f"ERROR: {INDEX_FILE} not found. Run export_index_json.py first.")
        sys.exit(1)

    env = load_env()
    if not env.get("SERVICE_API_KEY"):
        print("ERROR: .env file missing or SERVICE_API_KEY not set.")
        print("Make sure you ran: AIO_CLI_ENV=stage aio app deploy")
        sys.exit(1)

    print(f"Reading {INDEX_FILE} ({INDEX_FILE.stat().st_size // 1024} KB)...")
    data = INDEX_FILE.read_bytes()

    print("Getting access token...")
    token = get_access_token(env)

    org_id = env.get("AIO_RUNTIME_NAMESPACE", "").split("_")[0]
    project_id = env.get("SERVICE_API_KEY", "")

    print(f"Uploading to Adobe I/O Files as '{FILE_NAME}'...")
    r = upload_to_files(token, org_id, project_id, data)

    if r.status_code in (200, 201):
        print(f"Upload successful: {r.status_code}")
    else:
        print(f"Upload failed: {r.status_code} — {r.text[:300]}")
        sys.exit(1)


if __name__ == "__main__":
    main()
